// =============================================
// JUTT MOBILES — Seed Data (used for Supabase initial population)
// =============================================

export const CATEGORIES = [
  { id: 'cat-1', name: 'Mobile Accessories', slug: 'mobile-accessories', description: 'Cases, screen protectors, stands and more', icon: '📱', color: '#06b6d4' },
  { id: 'cat-2', name: 'Accessories', slug: 'accessories', description: 'Cables, mounts, tripods and everyday essentials', icon: '🔌', color: '#3b82f6' },
  { id: 'cat-3', name: 'Power Banks & Chargers', slug: 'power-banks', description: 'Fast chargers, power banks and wireless pads', icon: '⚡', color: '#f59e0b' },
  { id: 'cat-4', name: 'Earphones & Headsets', slug: 'earphones', description: 'TWS earbuds, neckbands, and studio headphones', icon: '🎧', color: '#8b5cf6' },
  { id: 'cat-5', name: 'Smart Watches', slug: 'smart-watches', description: 'Fitness bands, AMOLED smartwatches and GPS trackers', icon: '⌚', color: '#10b981' },
  { id: 'cat-6', name: 'Gaming', slug: 'gaming', description: 'Controllers, triggers, cooling fans and gaming headsets', icon: '🎮', color: '#ef4444' },
  { id: 'cat-7', name: 'Tech Gadgets', slug: 'tech-gadgets', description: 'Bluetooth speakers, ring lights, smart plugs and more', icon: '💡', color: '#ec4899' },
];

export const PRODUCTS = [
  // Mobile Accessories
  {
    id: 'mb-1', sku: 'JM-MB-001', name: 'Jutt Tempered Glass Screen Protector', slug: 'mb-1',
    category_id: 'cat-1', category_slug: 'mobile-accessories',
    price: 350, sale_price: 299, stock_quantity: 150, status: 'published',
    badge: 'New', rating: 4.5, review_count: 38,
    short_description: 'Ultra-clear 9H hardness tempered glass screen protector with full coverage.',
    description: 'Protect your screen with Jutt premium tempered glass. 9H hardness rating offers superior scratch resistance. Easy bubble-free installation kit included.',
    images: ['/assets/feature-product-BP1DexGI.jpg'],
    specifications: { 'Hardness': '9H', 'Material': 'Tempered Glass', 'Coverage': 'Full', 'Thickness': '0.3mm', 'Oleophobic Coating': 'Yes', 'Touch Response': '99%' },
  },
  {
    id: 'mb-2', sku: 'JM-MB-002', name: 'Jutt MagSafe Silicone Phone Case', slug: 'mb-2',
    category_id: 'cat-1', category_slug: 'mobile-accessories',
    price: 1199, sale_price: 899, stock_quantity: 85, status: 'published',
    badge: null, rating: 4.7, review_count: 56,
    short_description: 'Premium liquid silicone case with built-in MagSafe magnet ring for wireless charging.',
    description: 'Crafted from premium liquid silicone with a soft microfiber lining, this MagSafe-compatible case perfectly balances protection and elegance. Features precise cutouts and a raised bezel for screen and camera protection.',
    images: ['/assets/powerbank-4-17eCjlqr.jpg'],
    specifications: { 'Material': 'Liquid Silicone', 'Compatibility': 'iPhone 13/14/15 Series', 'MagSafe': 'Yes', 'Drop Protection': '2m', 'Colors Available': '8' },
  },
  {
    id: 'mb-3', sku: 'JM-MB-003', name: 'Jutt Foldable Tablet Stand Aluminium', slug: 'mb-3',
    category_id: 'cat-1', category_slug: 'mobile-accessories',
    price: 1499, sale_price: 1299, stock_quantity: 40, status: 'published',
    badge: 'Hot', rating: 4.6, review_count: 29,
    short_description: 'Adjustable aluminium alloy desktop stand for phones and tablets up to 13".',
    description: 'Sleek and sturdy aluminium alloy tablet stand with 360° rotation and adjustable angle. Anti-slip silicone pads prevent scratches and keep devices secure. Folds flat for travel convenience.',
    images: ['/assets/powerbank-3-Dzxoht3C.jpg'],
    specifications: { 'Material': 'Aluminium Alloy', 'Device Size': 'Up to 13"', 'Adjustable Angle': 'Yes', 'Rotation': '360°', 'Foldable': 'Yes', 'Weight': '280g' },
  },
  {
    id: 'mb-4', sku: 'JM-MB-004', name: 'Jutt USB-C to Lightning Braided Cable 1m', slug: 'mb-4',
    category_id: 'cat-1', category_slug: 'mobile-accessories',
    price: 799, sale_price: 599, stock_quantity: 200, status: 'published',
    badge: null, rating: 4.4, review_count: 72,
    short_description: 'Premium braided USB-C to Lightning cable with 30W fast charging support.',
    description: 'Double-braided nylon cable with reinforced connector heads for durability. Supports 30W PD fast charging and high-speed data transfer.',
    images: ['/assets/powerbank-2-l4eDv4NK.jpg'],
    specifications: { 'Length': '1m', 'Material': 'Braided Nylon', 'Power Delivery': '30W', 'Data Speed': 'USB 2.0', 'MFi Certified': 'Yes' },
  },

  // Accessories
  {
    id: 'ac-1', sku: 'JM-AC-001', name: 'Jutt 3-in-1 Charging Cable Braided', slug: 'ac-1',
    category_id: 'cat-2', category_slug: 'accessories',
    price: 899, sale_price: 699, stock_quantity: 120, status: 'published',
    badge: null, rating: 4.5, review_count: 91,
    short_description: 'Charge all your devices with one cable — Lightning, USB-C, and Micro USB.',
    description: 'Premium braided 3-in-1 multi-charging cable compatible with all major device types. Tangle-free design with 25W fast charging. 1.2m length with retractable ends.',
    images: ['/assets/powerbank-2-l4eDv4NK.jpg'],
    specifications: { 'Connectors': 'Lightning, USB-C, Micro-USB', 'Length': '1.2m', 'Power': '25W Max', 'Material': 'Braided Nylon', 'Compatibility': 'Universal' },
  },
  {
    id: 'ac-2', sku: 'JM-AC-002', name: 'Jutt Universal Phone Holder Car Mount', slug: 'ac-2',
    category_id: 'cat-2', category_slug: 'accessories',
    price: 1199, sale_price: 999, stock_quantity: 65, status: 'published',
    badge: 'New', rating: 4.3, review_count: 44,
    short_description: 'Gravity-sensing car mount with CD slot and dashboard mounting options.',
    description: 'Auto-lock gravity car mount compatible with 4" to 7" phones. Fits CD slot or dashboard with included suction cup. One-handed operation with 360° rotation.',
    images: ['/assets/powerbank-4-17eCjlqr.jpg'],
    specifications: { 'Mount Type': 'CD Slot / Dashboard', 'Device Size': '4" - 7"', 'Rotation': '360°', 'Lock Type': 'Gravity Auto-Lock', 'Material': 'ABS + Silicone' },
  },
  {
    id: 'ac-3', sku: 'JM-AC-003', name: 'Jutt Bluetooth Selfie Tripod Stand', slug: 'ac-3',
    category_id: 'cat-2', category_slug: 'accessories',
    price: 1899, sale_price: 1599, stock_quantity: 35, status: 'published',
    badge: null, rating: 4.6, review_count: 33,
    short_description: 'Extendable Bluetooth remote shutter tripod, doubles as a selfie stick.',
    description: 'Multi-function tripod that extends from 21cm to 160cm. Detachable Bluetooth remote works up to 10m range. Foldable and ultra-lightweight for travel.',
    images: ['/assets/earphone-2-DGaIUvk1.jpg'],
    specifications: { 'Extended Length': 'Up to 160cm', 'Bluetooth Range': '10m', 'Battery': 'Built-in rechargeable', 'Compatibility': 'iOS & Android', 'Weight': '200g' },
  },
  {
    id: 'ac-4', sku: 'JM-AC-004', name: 'Jutt OTG Type-C Card Reader', slug: 'ac-4',
    category_id: 'cat-2', category_slug: 'accessories',
    price: 450, sale_price: 399, stock_quantity: 300, status: 'published',
    badge: null, rating: 4.1, review_count: 57,
    short_description: 'Compact OTG card reader supporting SD, TF, and USB-A simultaneously.',
    description: 'All-in-one USB-C hub with SD card reader, TF card reader, and USB-A port. Supports simultaneous reading. Plug-and-play with no driver installation required.',
    images: ['/assets/powerbank-1-B6KU1BY8.jpg'],
    specifications: { 'Interface': 'USB-C', 'Ports': 'SD, TF, USB-A', 'Transfer Speed': 'Up to 5Gbps', 'Plug & Play': 'Yes', 'OS': 'Android, MacOS, Windows' },
  },

  // Power Banks & Chargers
  {
    id: 'pb-1', sku: 'JM-PB-001', name: 'Jutt Slim 10000mAh Power Bank', slug: 'pb-1',
    category_id: 'cat-3', category_slug: 'power-banks',
    price: 2999, sale_price: 2499, stock_quantity: 55, status: 'published',
    badge: null, rating: 4.8, review_count: 124,
    short_description: 'Ultra-slim 10000mAh power bank with 22.5W fast charging and dual output.',
    description: 'Jutt Slim is the world-class ultra-thin power bank at just 12mm thick. Features 22.5W input/output, LED indicator display, and dual USB-A + USB-C outputs. Charges an iPhone 15 from 0 to 100% in under 90 minutes.',
    images: ['/assets/powerbank-1-B6KU1BY8.jpg'],
    specifications: { 'Capacity': '10,000 mAh', 'Output': '22.5W Max', 'Input': 'USB-C 22.5W', 'Ports': '2x USB-A, 1x USB-C', 'Thickness': '12mm', 'Weight': '186g' },
  },
  {
    id: 'pb-2', sku: 'JM-PB-002', name: 'Jutt 65W GaN Fast Wall Charger', slug: 'pb-2',
    category_id: 'cat-3', category_slug: 'power-banks',
    price: 3999, sale_price: 3499, stock_quantity: 80, status: 'published',
    badge: 'New', rating: 4.9, review_count: 89,
    short_description: 'Compact 65W GaN charger with 3 ports for simultaneous laptop, phone, and tablet charging.',
    description: 'Next-gen GaN (Gallium Nitride) technology delivers 65W total power in a package smaller than a credit card. PD 3.0 + QC 4.0 compatible. Charge your MacBook Pro from 0-50% in just 30 minutes.',
    images: ['/assets/powerbank-2-l4eDv4NK.jpg'],
    specifications: { 'Total Power': '65W', 'Technology': 'GaN (Gallium Nitride)', 'Ports': '2x USB-C PD, 1x USB-A QC', 'Standards': 'PD3.0, QC4.0', 'Input': '100-240V', 'Safety': 'OVP, OCP, OTP' },
  },
  {
    id: 'pb-3', sku: 'JM-PB-003', name: 'Jutt 20000mAh Digital Display Power Bank', slug: 'pb-3',
    category_id: 'cat-3', category_slug: 'power-banks',
    price: 4999, sale_price: 4499, stock_quantity: 30, status: 'published',
    badge: null, rating: 4.7, review_count: 67,
    short_description: 'High-capacity 20000mAh power bank with digital display showing exact battery percentage.',
    description: 'Never guess your charge level again. The built-in LCD display shows precise battery percentage. 22.5W bidirectional fast charging with pass-through support. Charge 3 devices simultaneously.',
    images: ['/assets/powerbank-3-Dzxoht3C.jpg'],
    specifications: { 'Capacity': '20,000 mAh', 'Display': 'LCD Digital Percentage', 'Output Power': '22.5W', 'Ports': '3 (USB-C, 2x USB-A)', 'Weight': '420g', 'Pass-Through': 'Yes' },
  },
  {
    id: 'pb-4', sku: 'JM-PB-004', name: 'Jutt MagSafe Wireless Charging Pad', slug: 'pb-4',
    category_id: 'cat-3', category_slug: 'power-banks',
    price: 2799, sale_price: 2499, stock_quantity: 70, status: 'published',
    badge: 'Hot', rating: 4.6, review_count: 42,
    short_description: '15W MagSafe-compatible wireless charging pad with LED indicator.',
    description: 'Perfectly aligned MagSafe wireless charging for iPhones. Delivers 15W for MagSafe-compatible devices, 10W for Qi2, and 5W for standard Qi. Anti-slip base with foreign object detection.',
    images: ['/assets/powerbank-4-17eCjlqr.jpg'],
    specifications: { 'Max Output': '15W (MagSafe)', 'Standards': 'MagSafe, Qi2, Qi', 'Cable': 'USB-C 1.5m', 'FOD': 'Yes', 'LED Indicator': 'Yes' },
  },

  // Earphones & Headsets
  {
    id: 'ep-1', sku: 'JM-EP-001', name: 'Jutt TWS Pro Wireless Earbuds', slug: 'ep-1',
    category_id: 'cat-4', category_slug: 'earphones',
    price: 2699, sale_price: 2299, stock_quantity: 45, status: 'published',
    badge: null, rating: 4.7, review_count: 156,
    short_description: 'True wireless earbuds with ANC, 30hr total battery, and IPX5 water resistance.',
    description: 'Jutt TWS Pro delivers a premium sound experience with active noise cancellation and deep bass drivers. Earbuds last 8 hours, case extends to 30 hours. Touch controls with voice assistant support.',
    images: ['/assets/earphone-1-DYzzoxEI.jpg'],
    specifications: { 'Driver': '13mm Dynamic', 'ANC': 'Active Noise Cancellation', 'Battery': '8hr + 22hr case', 'IPX Rating': 'IPX5', 'Bluetooth': '5.3', 'Latency': '35ms Gaming Mode' },
  },
  {
    id: 'ep-2', sku: 'JM-EP-002', name: 'Jutt Neckband Bluetooth Earphones', slug: 'ep-2',
    category_id: 'cat-4', category_slug: 'earphones',
    price: 2199, sale_price: 1899, stock_quantity: 60, status: 'published',
    badge: 'New', rating: 4.5, review_count: 88,
    short_description: 'Neckband earphones with magnetic eartips, 24hr battery, and cVc 8.0 mic.',
    description: 'Stay connected all day with Jutt Neckband earphones. Magnetic eartips snap together when not in use. cVc 8.0 noise-cancelling microphone for crystal-clear calls.',
    images: ['/assets/earphone-2-DGaIUvk1.jpg'],
    specifications: { 'Type': 'Neckband', 'Battery': '24 hours', 'Bluetooth': '5.0', 'Mic': 'cVc 8.0', 'Charging': 'USB-C', 'Magnetic': 'Yes' },
  },
  {
    id: 'ep-3', sku: 'JM-EP-003', name: 'Jutt Studio Over-Ear Headphones', slug: 'ep-3',
    category_id: 'cat-4', category_slug: 'earphones',
    price: 5999, sale_price: 5499, stock_quantity: 20, status: 'published',
    badge: null, rating: 4.9, review_count: 43,
    short_description: 'Professional studio headphones with 40mm drivers, foldable design, and 50hr battery.',
    description: 'Studio-grade sound reproduction with custom-tuned 40mm neodymium drivers. Foldable design with memory foam earcups. Works wired (3.5mm) or wirelessly via Bluetooth 5.2.',
    images: ['/assets/earphone-3-DrQ_pPtF.jpg'],
    specifications: { 'Driver': '40mm Neodymium', 'Frequency': '20Hz - 20kHz', 'Battery': '50 hours', 'Bluetooth': '5.2', 'Wired Mode': '3.5mm AUX', 'Foldable': 'Yes' },
  },

  // Smart Watches
  {
    id: 'wt-1', sku: 'JM-WT-001', name: 'Jutt Smart Watch S9 Pro AMOLED', slug: 'wt-1',
    category_id: 'cat-5', category_slug: 'smart-watches',
    price: 6499, sale_price: 4999, stock_quantity: 35, status: 'published',
    badge: null, rating: 4.8, review_count: 201,
    short_description: 'AMOLED smartwatch with 100+ sport modes, Bluetooth calling, and 7-day battery.',
    description: 'The Jutt S9 Pro features a gorgeous 1.96" AMOLED display with always-on capabilities. Bluetooth calling, 100+ sport modes, heart rate/SpO2/stress monitoring. 7-day battery with customizable watch faces.',
    images: ['/assets/earphone-3-DrQ_pPtF.jpg'],
    specifications: { 'Display': '1.96" AMOLED', 'Battery': '7 days', 'Sport Modes': '100+', 'Bluetooth Calling': 'Yes', 'Health': 'HR, SpO2, Stress, Sleep', 'Water Resistance': '5ATM' },
  },
  {
    id: 'wt-2', sku: 'JM-WT-002', name: 'Jutt Fitness Band Pulse 2', slug: 'wt-2',
    category_id: 'cat-5', category_slug: 'smart-watches',
    price: 2199, sale_price: 1799, stock_quantity: 90, status: 'published',
    badge: 'New', rating: 4.4, review_count: 78,
    short_description: 'Slim fitness band with continuous heart rate tracking, sleep analysis, and 14-day battery.',
    description: 'Track your health around the clock with Jutt Fitness Band Pulse 2. Automatic workout detection, female health tracking, and smart notifications. 1.47" AMOLED touch screen with always-on option.',
    images: ['/assets/earphone-2-DGaIUvk1.jpg'],
    specifications: { 'Display': '1.47" AMOLED', 'Battery': '14 days', 'Water Resistance': '5ATM', 'Sensors': 'HR, SpO2, Gyroscope', 'Auto Detection': '6 workouts', 'Charging': 'Magnetic' },
  },
  {
    id: 'wt-3', sku: 'JM-WT-003', name: 'Jutt Ultra Sport Watch Titanium', slug: 'wt-3',
    category_id: 'cat-5', category_slug: 'smart-watches',
    price: 11999, sale_price: 8999, stock_quantity: 12, status: 'published',
    badge: 'Hot', rating: 4.9, review_count: 34,
    short_description: 'Premium titanium sports watch with GPS, offline maps, and 21-day battery life.',
    description: 'Built for serious athletes. Aircraft-grade titanium case with sapphire crystal glass. Built-in GPS with offline topographic maps, altimeter, barometer, and compass. MIL-STD-810H military-grade durability.',
    images: ['/assets/earphone-1-DYzzoxEI.jpg'],
    specifications: { 'Case': 'Titanium + Sapphire Glass', 'GPS': 'Multi-band GNSS', 'Battery': 'GPS Mode 21 days', 'Durability': 'MIL-STD-810H', 'Dive Rating': '100m', 'Maps': 'Offline Topographic' },
  },

  // Gaming
  {
    id: 'gm-1', sku: 'JM-GM-001', name: 'Jutt Wireless Game Controller Pro', slug: 'gm-1',
    category_id: 'cat-6', category_slug: 'gaming',
    price: 3499, sale_price: 2999, stock_quantity: 28, status: 'published',
    badge: null, rating: 4.6, review_count: 112,
    short_description: 'Multi-platform wireless game controller with 1000Hz polling and hall effect sticks.',
    description: 'Professional wireless controller with Bluetooth 5.0 + USB-C wired mode. Hall effect joysticks eliminate drift. 10-hour battery, programmable back buttons, and vibration feedback.',
    images: ['/assets/powerbank-4-17eCjlqr.jpg'],
    specifications: { 'Connection': 'Bluetooth 5.0 + USB-C', 'Sticks': 'Hall Effect (Drift-Free)', 'Battery': '10 hours', 'Polling Rate': '1000Hz', 'Platforms': 'PC, Android, iOS', 'Back Buttons': '4 programmable' },
  },
  {
    id: 'gm-2', sku: 'JM-GM-002', name: 'Jutt RGB Mobile Gaming Trigger Set', slug: 'gm-2',
    category_id: 'cat-6', category_slug: 'gaming',
    price: 999, sale_price: 799, stock_quantity: 150, status: 'published',
    badge: 'New', rating: 4.3, review_count: 67,
    short_description: 'Sensitive shoulder trigger buttons with RGB lighting for mobile PUBG/COD gaming.',
    description: 'Clip-on L1/R1 trigger buttons transform your phone into a gaming console. Ultra-sensitive 30-degree angle triggers, RGB underglow lighting, and universal compatibility.',
    images: ['/assets/earphone-4-D8h7Lxv4.jpg'],
    specifications: { 'Sensitivity': 'Ultra-sensitive', 'Lighting': 'RGB', 'Compatibility': 'Universal 4" - 6.7"', 'Material': 'ABS Plastic', 'Trigger Angle': '30°' },
  },
  {
    id: 'gm-3', sku: 'JM-GM-003', name: 'Jutt Gaming Headset 7.1 Surround', slug: 'gm-3',
    category_id: 'cat-6', category_slug: 'gaming',
    price: 4999, sale_price: 4499, stock_quantity: 22, status: 'published',
    badge: null, rating: 4.7, review_count: 88,
    short_description: '7.1 virtual surround sound gaming headset with noise-cancelling mic and RGB.',
    description: 'Immersive 7.1 virtual surround sound with 50mm drivers for competitive gaming. Detachable noise-cancelling microphone, premium memory foam earcups, and RGB lighting effects.',
    images: ['/assets/earphone-3-DrQ_pPtF.jpg'],
    specifications: { 'Driver': '50mm', 'Surround': '7.1 Virtual', 'Microphone': 'Detachable NC Mic', 'RGB': 'Yes', 'Connection': 'USB + 3.5mm AUX', 'Weight': '320g' },
  },

  // Tech Gadgets
  {
    id: 'gd-1', sku: 'JM-GD-001', name: 'Jutt Mini Bluetooth Speaker Boom', slug: 'gd-1',
    category_id: 'cat-7', category_slug: 'tech-gadgets',
    price: 2499, sale_price: 1999, stock_quantity: 48, status: 'published',
    badge: null, rating: 4.5, review_count: 94,
    short_description: 'Compact 10W portable Bluetooth speaker with 360° audio and IPX7 waterproofing.',
    description: 'Big sound in a compact body. Jutt Boom delivers 10W of rich 360° audio with deep bass via passive radiator. IPX7 waterproof — take it to the beach, pool, or shower. 12-hour playtime.',
    images: ['/assets/feature-product-BP1DexGI.jpg'],
    specifications: { 'Power': '10W', 'Audio': '360° Omnidirectional', 'Waterproof': 'IPX7', 'Battery': '12 hours', 'Bluetooth': '5.2', 'TWS Pairing': 'Yes' },
  },
  {
    id: 'gd-2', sku: 'JM-GD-002', name: 'Jutt LED Ring Light 10" with Tripod', slug: 'gd-2',
    category_id: 'cat-7', category_slug: 'tech-gadgets',
    price: 2999, sale_price: 2499, stock_quantity: 33, status: 'published',
    badge: 'Creator', rating: 4.6, review_count: 51,
    short_description: '10" LED ring light with adjustable tripod stand and phone holder for content creation.',
    description: 'Professional studio lighting at home. 3 color modes (3200K-5500K-6500K), 10 brightness levels. Includes adjustable 50-160cm tripod, universal phone holder, and remote control.',
    images: ['/assets/powerbank-4-17eCjlqr.jpg'],
    specifications: { 'Size': '10 inches', 'Color Temp': '3200K / 5500K / 6500K', 'Brightness': '10 Levels', 'Tripod Height': '50-160cm', 'Power': 'USB', 'Remote': 'Included' },
  },
  {
    id: 'gd-3', sku: 'JM-GD-003', name: 'Jutt Smart WiFi Plug Adapter', slug: 'gd-3',
    category_id: 'cat-7', category_slug: 'tech-gadgets',
    price: 1499, sale_price: 1299, stock_quantity: 100, status: 'published',
    badge: 'Smart', rating: 4.2, review_count: 39,
    short_description: 'WiFi smart plug with energy monitoring, voice control (Alexa/Google), and scheduling.',
    description: 'Transform any appliance into a smart one. Monitor energy usage in real-time, set timers and schedules via app, and use voice control with Alexa and Google Assistant.',
    images: ['/assets/powerbank-1-B6KU1BY8.jpg'],
    specifications: { 'WiFi': '2.4GHz 802.11 b/g/n', 'Voice Control': 'Alexa, Google', 'Energy Monitor': 'Yes', 'App': 'iOS & Android', 'Max Load': '16A / 3680W', 'Timer': 'Yes' },
  },

  // Special WIWU Product
  {
    id: 'wiwu-3in1', sku: 'JM-WIWU-001', name: 'WIWU 3 in 1 Wireless Charger Speaker Wi-W022', slug: 'wiwu-3in1-wireless-charger',
    category_id: 'cat-3', category_slug: 'power-banks',
    price: 9999, sale_price: 8999, stock_quantity: 18, status: 'published',
    badge: 'Premium', rating: 4.9, review_count: 28,
    short_description: 'Charge phone, earbuds, and smartwatch simultaneously with crystal-clear audio output.',
    description: 'The WIWU Wi-W022 is the ultimate desk companion. A premium 3-in-1 wireless charging station combined with a high-fidelity Bluetooth speaker. Charge your phone (15W MagSafe / 10W Qi), earbuds (5W), and smartwatch all at once while enjoying rich, room-filling sound.',
    images: ['/assets/feature-product-BP1DexGI.jpg'],
    specifications: { 'Phone Charging': '15W MagSafe / 10W Qi2', 'Earbuds Charging': '5W', 'Watch Charging': '3W', 'Speaker Power': '10W Hi-Fi', 'Bluetooth': '5.3 (Speaker)', 'Material': 'Premium Aluminium + Fabric' },
  },
];

export const STORE_SETTINGS = {
  shop_name: 'Jutt Mobiles',
  shop_tagline: 'Premium Mobile Accessories in Pakistan',
  support_email: 'support@juttmobile.pk',
  support_phone: '+92 300 1234567',
  whatsapp_number: '923001234567',
  address: 'Lahore, Punjab, Pakistan',
  shipping_flat_rate: 250,
  free_shipping_threshold: 2000,
  free_shipping_enabled: true,
  cod_enabled: true,
  bank_transfer_enabled: true,
  bank_name: 'HBL (Habib Bank)',
  account_title: 'Jutt Mobiles Pakistan',
  account_number: '0001-1234567890',
  iban: 'PK36HABB0000000001234567',
  currency: 'PKR',
  currency_symbol: 'Rs.',
  announcement_bar: 'Free delivery on orders above Rs. 2,000 | 7-day easy returns | Authentic products, warranty included',
};

export const DISCOUNT_CODES = [
  { code: 'JUTT10', type: 'percentage', value: 10, min_order: 1000, active: true },
  { code: 'JUTT20', type: 'percentage', value: 20, min_order: 3000, active: true },
  { code: 'SAVE500', type: 'fixed', value: 500, min_order: 2000, active: true },
];

export const SAMPLE_REVIEWS = [
  { id: 'r1', product_id: 'pb-1', author: 'Ahmed Raza', rating: 5, comment: 'Excellent product! Fast charging and very slim. Highly recommended.', created_at: '2026-05-10' },
  { id: 'r2', product_id: 'pb-1', author: 'Sara Khan', rating: 4, comment: 'Great power bank, light and portable. Wish it had more capacity.', created_at: '2026-05-18' },
  { id: 'r3', product_id: 'ep-1', author: 'Bilal Ahmad', rating: 5, comment: 'Sound quality is amazing! ANC is very effective. Worth every penny.', created_at: '2026-06-01' },
  { id: 'r4', product_id: 'wt-1', author: 'Fatima Ali', rating: 5, comment: 'Best smartwatch I\'ve owned. The AMOLED display is gorgeous!', created_at: '2026-06-10' },
];
